#ifndef __MTK3BSP2_MQTT_SERVER_H__
#define __MTK3BSP2_MQTT_SERVER_H__

#define MAX_MQTT_CLIENTS			10
#define MAX_MQTT_TOPICS				5
#define MAX_MQTT_TOPIC_LENGTH		50
#define MAX_MQTT_MESSAGE_LENGTH		100

#define MQTT_HEADER_TYPE_MASK		0xF0

#define MQTT_HEADER_TYPE_CONNECT	0x10
#define MQTT_HEADER_TYPE_CONNACK	0x20
#define MQTT_HEADER_TYPE_PUBLISH	0x30
#define MQTT_HEADER_TYPE_SUBSCRIBE	0x80
#define MQTT_HEADER_TYPE_SUBACK		0x90

#define MQTT_HEADER_QOS_MASK		0x06
#define MQTT_HEADER_RETAIN_MASK		0x01

err_t mtk3bsp2_mqtt_broker_init(void);

#endif /* __MTK3BSP2_MQTT_SERVER_H__ */
